version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --no-restore

workflows:
  version: 2
  build_workflow:
    jobs:
      - build